export const CREATE_EMP_REQUEST = "CREATE_EMP_REQUEST";
export const CREATE_EMP_SUCCESS = "CREATE_EMP_SUCCESS";
export const CREATE_EMP_FAILURE = "CREATE_EMP_FAILURE";

export const FETCH_EMPS_REQUEST = "FETCH_EMPS_REQUEST";
export const FETCH_EMPS_SUCCESS = "FETCH_EMPS_SUCCESS";
export const FETCH_EMPS_FAILURE = "FETCH_EMPS_FAILURE";

export const FETCH_EMP_REQUEST = "FETCH_EMP_REQUEST";
export const FETCH_EMP_SUCCESS = "FETCH_EMP_SUCCESS";
export const FETCH_EMP_FAILURE = "FETCH_EMP_FAILURE";

export const UPDATE_EMP_REQUEST = "UPDATE_EMP_REQUEST";
export const UPDATE_EMP_SUCCESS = "UPDATE_EMP_SUCCESS";
export const UPDATE_EMP_FAILURE = "UPDATE_EMP_FAILURE";

export const DELETE_EMP_REQUEST = "DELETE_EMP_REQUEST";
export const DELETE_EMP_SUCCESS = "DELETE_EMP_SUCCESS";
export const DELETE_EMP_FAILURE = "DELETE_EMP_FAILURE";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAILURE = "CREATE_FAILURE";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const RESET_STATE = "RESET_STATE";

export const NAVIGATE_TO = "NAVIGATE_TO";